#@PydevCodeAnalysisIgnore
"""empty message

Revision ID: aacf65cac9db
Revises: b23b12b13544
Create Date: 2018-11-26 13:52:32.140898

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm.session import Session
import pickle
from imct.app.models import XmlNodeAttrModel, XmlNodeAttrValModel
from imct.app.enums.xml_node import XmlNodeAttrEnum
from sqlalchemy.orm import joinedload


# revision identifiers, used by Alembic.
revision = 'aacf65cac9db'
down_revision = 'b23b12b13544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_node_instance', sa.Column('code', sa.Text(), nullable=True))
    bind = op.get_bind()
    session = Session(bind=bind)
    for attr_val in session.query(XmlNodeAttrValModel).join(XmlNodeAttrValModel.attr).options(joinedload(XmlNodeAttrValModel.attr)).filter(XmlNodeAttrModel.name == XmlNodeAttrEnum.CODE).all():
        attr_val.node_inst.code = attr_val.value_obj
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xml_node_instance', 'code')
    # ### end Alembic commands ###
